[package]
name = "rwcell"
version = "0.1.0"
edition = "2018"

description = "RefCell except not"
categories = ["no-std"]

[dependencies]
const-default = { version = "^0.1.0", git = "https://github.com/AerialX/const-default.rs", optional = true }
